# Generated by Django 4.2.26 on 2025-11-12 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('advertiser', 'Рекламодатель'), ('publisher', 'Веб-мастер')], max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('rating', models.FloatField(default=5.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'Технологии'), ('sports', 'Спорт'), ('entertainment', 'Развлечения'), ('news', 'Новости'), ('education', 'Образование'), ('business', 'Бизнес'), ('other', 'Другое')], max_length=50)),
                ('daily_visitors', models.IntegerField(help_text='Примерное количество посетителей в день')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена за размещение', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'publisher'}, on_delete=django.db.models.deletion.CASCADE, to='ads.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AdOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, help_text='Сообщение от рекламодателя владельцу площадки')),
                ('advertiser', models.ForeignKey(limit_choices_to={'user_type': 'advertiser'}, on_delete=django.db.models.deletion.CASCADE, to='ads.userprofile')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.site')),
            ],
        ),
    ]
