# Generated by Django 4.2.26 on 2025-11-13 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('buy', 'Купить рекламу'), ('sell', 'Продать рекламу')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'Технологии'), ('sports', 'Спорт'), ('entertainment', 'Развлечения'), ('news', 'Новости'), ('education', 'Образование'), ('business', 'Бизнес'), ('other', 'Другое')], max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Бюджет или цена', max_digits=10)),
                ('contact_info', models.CharField(help_text='Контактная информация', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='owner',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('advertiser', 'Рекламодатель'), ('publisher', 'Веб-мастер')], default='advertiser', max_length=20),
        ),
        migrations.DeleteModel(
            name='AdOrder',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.AddField(
            model_name='ad',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.userprofile'),
        ),
    ]
